Config 				  = {}
Config.cooldown		  = 1000

Config.Weapons = {
	"WEAPON_SNSPISTOL",
	"WEAPON_PISTOL",
	"WEAPON_VINTAGEPISTOL",
	"WEAPON_PISTOL50",
	"WEAPON_REVOLVER",
	"WEAPON_MICROSMG",
	"WEAPON_MINISMG",
	"WEAPON_MACHINEPISTOL",
	"WEAPON_DBSHOTGUN",
	"WEAPON_MUSKET",
	"WEAPON_ASSAULTRIFLEL",
	"WEAPON_COMPACTRIFLE",
	"WEAPON_GUSENBERG",

	"WEAPON_SMG",
	"WEAPON_PUMPSHOTGUN",
	"WEAPON_CARBINERIFLE",
	"WEAPON_ASSAULTSMG",

	"WEAPON_CROWBAR",
	"WEAPON_BAT",
	"WEAPON_MACHETE",
	"WEAPON_FLASHLIGHT",
	"WEAPON_DAGGER",
	"WEAPON_GOLFCLUB",
	"WEAPON_NIGHTSTICK",
	"WEAPON_WRENCH",

	"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",

}
